/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: ["class"],
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	theme: {
		extend: {
			keyframes: {
				"accordion-down": {
					from: { height: "0" },
					to: { height: "var(--radix-accordion-content-height)" },
				},
				"accordion-up": {
					from: { height: "var(--radix-accordion-content-height)" },
					to: { height: "0" },
				},
				"record-pulse": {
					"0%, 100%": { boxShadow: "0 0 8px rgba(239, 68, 68, 0.15)" },
					"50%": { boxShadow: "0 0 16px rgba(239, 68, 68, 0.4)" },
				},
				"mic-panel-in": {
					from: { opacity: "0", transform: "translateY(4px)" },
					to: { opacity: "1", transform: "translateY(0)" },
				},
			},
			animation: {
				"accordion-down": "accordion-down 0.2s ease-out",
				"accordion-up": "accordion-up 0.2s ease-out",
				"record-pulse": "record-pulse 1.5s ease-in-out infinite",
				"mic-panel-in": "mic-panel-in 0.15s ease-out",
			},
			boxShadow: {
				"hud-bar": "0 2px 16px rgba(0, 0, 0, 0.25), 0 0 40px rgba(100, 80, 200, 0.08)",
				"mic-panel": "0 2px 12px rgba(0, 0, 0, 0.2), 0 0 30px rgba(100, 80, 200, 0.06)",
			},
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
			},
			colors: {
				ds: {
					surface: "var(--ds-surface)",
					ink: "var(--ds-ink)",
					muted: "var(--ds-muted)",
					line: "var(--ds-line)",
					accent: "var(--ds-accent)",
					"on-accent": "var(--ds-on-accent)",
					"surface-raised": "var(--ds-surface-raised)",
					"surface-sunken": "var(--ds-surface-sunken)",
					"ink-soft": "var(--ds-ink-soft)",
					"ink-faint": "var(--ds-ink-faint)",
					"ink-wash": "var(--ds-ink-wash)",
					"ink-whisper": "var(--ds-ink-whisper)",
					chip: "var(--ds-chip)",
					panel: "var(--ds-panel)",
					"panel-deep": "var(--ds-panel-deep)",
					"on-panel": "var(--ds-on-panel)",
					"on-panel-soft": "var(--ds-on-panel-soft)",
					"on-panel-muted": "var(--ds-on-panel-muted)",
					"on-panel-faint": "var(--ds-on-panel-faint)",
					"on-panel-strong-line": "var(--ds-on-panel-strong-line)",
					"on-panel-line": "var(--ds-on-panel-line)",
					"on-panel-wash": "var(--ds-on-panel-wash)",
					"on-panel-hover": "var(--ds-on-panel-hover)",
					"on-panel-track": "var(--ds-on-panel-track)",
					"accent-tint": "var(--ds-accent-tint)",
					"accent-tint-2": "var(--ds-accent-tint-2)",
					"accent-wash": "var(--ds-accent-wash)",
					"accent-whisper": "var(--ds-accent-whisper)",
					"accent-100": "var(--ds-accent-100)",
					"accent-200": "var(--ds-accent-200)",
					"accent-strong": "var(--ds-accent-strong)",
					"accent-strong-soft": "var(--ds-accent-strong-soft)",
					rec: "var(--ds-rec)",
					"rec-wash": "var(--ds-rec-wash)",
					"rec-ink": "var(--ds-rec-ink)",
					"rec-soft": "var(--ds-rec-soft)",
					forest: "var(--ds-forest)",
					signal: "var(--ds-signal)",
					"hud-bg": "var(--ds-hud-bg)",
					"hud-border": "var(--ds-hud-border)",
					"hud-group": "var(--ds-hud-group)",
					"hud-green": "var(--ds-hud-green)",
					"hud-red": "var(--ds-hud-red)",
					"editor-bg": "var(--ds-editor-bg)",
					"editor-accent": "var(--ds-editor-accent)",
				},
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},
				popover: {
					DEFAULT: "hsl(var(--popover))",
					foreground: "hsl(var(--popover-foreground))",
				},
				primary: {
					DEFAULT: "hsl(var(--primary))",
					foreground: "hsl(var(--primary-foreground))",
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary))",
					foreground: "hsl(var(--secondary-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				accent: {
					DEFAULT: "hsl(var(--accent))",
					foreground: "hsl(var(--accent-foreground))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				border: "hsl(var(--border))",
				input: "hsl(var(--input))",
				ring: "hsl(var(--ring))",
				chart: {
					1: "hsl(var(--chart-1))",
					2: "hsl(var(--chart-2))",
					3: "hsl(var(--chart-3))",
					4: "hsl(var(--chart-4))",
					5: "hsl(var(--chart-5))",
				},
			},
			fontFamily: {
				"ds-body": "var(--ds-font-body)",
				"ds-label": "var(--ds-font-label)",
				"ds-display": "var(--ds-font-display)",
				"ds-serif": "var(--ds-font-serif)",
			},
		},
	},
	plugins: [require("tailwindcss-animate")],
};
