export type DesignToken = {
	type: "color" | "number" | "string";
	light: string;
	dark: string;
};

export const DS_TOKENS = {
	"ds-surface": { type: "color", light: "#FFFCF7", dark: "#2F2F2F" },
	"ds-ink": { type: "color", light: "#2F2F2F", dark: "#FFFCF7" },
	"ds-muted": { type: "color", light: "#2F2F2F8C", dark: "#FFFCF78C" },
	"ds-line": { type: "color", light: "#2F2F2F24", dark: "#FFFCF724" },
	"ds-accent": { type: "color", light: "#82B09A", dark: "#82B09A" },
	"ds-on-accent": { type: "color", light: "#2F2F2F", dark: "#2F2F2F" },
	"ds-space": { type: "number", light: "16", dark: "16" },
	"ds-radius": { type: "number", light: "8", dark: "8" },
	"ds-font-size": { type: "number", light: "14", dark: "14" },
	"ds-font-body": { type: "string", light: "Inter", dark: "Inter" },
	"ds-font-label": { type: "string", light: "JetBrains Mono", dark: "JetBrains Mono" },
	"ds-font-display": { type: "string", light: "Inter Tight", dark: "Inter Tight" },
	"ds-font-serif": { type: "string", light: "Instrument Serif", dark: "Instrument Serif" },
	"ds-surface-raised": { type: "color", light: "#F9F5EC", dark: "#363636" },
	"ds-surface-sunken": { type: "color", light: "#F7F2E8", dark: "#292929" },
	"ds-ink-soft": { type: "color", light: "#2F2F2FB3", dark: "#FFFCF7B3" },
	"ds-ink-faint": { type: "color", light: "#2F2F2F66", dark: "#FFFCF766" },
	"ds-ink-wash": { type: "color", light: "#2F2F2F14", dark: "#FFFCF714" },
	"ds-ink-whisper": { type: "color", light: "#2F2F2F08", dark: "#FFFCF708" },
	"ds-chip": { type: "color", light: "#E8E4DC", dark: "#3A3A3A" },
	"ds-panel": { type: "color", light: "#2F2F2F", dark: "#242424" },
	"ds-panel-deep": { type: "color", light: "#242424", dark: "#1C1C1C" },
	"ds-on-panel": { type: "color", light: "#FFFCF7", dark: "#FFFCF7" },
	"ds-on-panel-soft": { type: "color", light: "#FFFCF7AA", dark: "#FFFCF7AA" },
	"ds-on-panel-muted": { type: "color", light: "#FFFCF78C", dark: "#FFFCF78C" },
	"ds-on-panel-faint": { type: "color", light: "#FFFCF766", dark: "#FFFCF766" },
	"ds-on-panel-strong-line": { type: "color", light: "#FFFCF74D", dark: "#FFFCF74D" },
	"ds-on-panel-line": { type: "color", light: "#FFFCF71F", dark: "#FFFCF71F" },
	"ds-on-panel-wash": { type: "color", light: "#FFFCF71A", dark: "#FFFCF71A" },
	"ds-on-panel-hover": { type: "color", light: "#FFFCF70F", dark: "#FFFCF70F" },
	"ds-on-panel-track": { type: "color", light: "#FFFCF733", dark: "#FFFCF733" },
	"ds-accent-tint": { type: "color", light: "#82B09A33", dark: "#82B09A33" },
	"ds-accent-tint-2": { type: "color", light: "#82B09A2E", dark: "#82B09A2E" },
	"ds-accent-wash": { type: "color", light: "#82B09A26", dark: "#82B09A26" },
	"ds-accent-whisper": { type: "color", light: "#82B09A1F", dark: "#82B09A1F" },
	"ds-accent-100": { type: "color", light: "#E7F1EC", dark: "#33564A" },
	"ds-accent-200": { type: "color", light: "#CFE4DA", dark: "#3F6A5A" },
	"ds-accent-strong": { type: "color", light: "#33564A", dark: "#A9CDBB" },
	"ds-accent-strong-soft": { type: "color", light: "#33564A99", dark: "#A9CDBB99" },
	"ds-rec": { type: "color", light: "#E4572E", dark: "#E4572E" },
	"ds-rec-wash": { type: "color", light: "#E4572E1F", dark: "#E4572E33" },
	"ds-rec-ink": { type: "color", light: "#B3431F", dark: "#F28B6B" },
	"ds-rec-soft": { type: "color", light: "#F28B6B", dark: "#F28B6B" },
	"ds-forest": { type: "color", light: "#142F18", dark: "#142F18" },
	"ds-signal": { type: "color", light: "#6BFF7E", dark: "#6BFF7E" },
	"ds-hud-bg": { type: "color", light: "#07080AE6", dark: "#07080AE6" },
	"ds-hud-border": { type: "color", light: "#FFFFFF1A", dark: "#FFFFFF1A" },
	"ds-hud-group": { type: "color", light: "#FFFFFF0B", dark: "#FFFFFF0B" },
	"ds-hud-green": { type: "color", light: "#4ADE80", dark: "#4ADE80" },
	"ds-hud-red": { type: "color", light: "#F87171", dark: "#F87171" },
	"ds-editor-bg": { type: "color", light: "#09090B", dark: "#09090B" },
	"ds-editor-accent": { type: "color", light: "#34B27B", dark: "#34B27B" },
} as const satisfies Record<string, DesignToken>;
